---
settings:
  name: Amazon FSx for ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,zh-cn,ko-kr
sidebar:
  product-family:
    name: Cloud Manager
    repo: cloud-manager-family
  entries:
  - title: Cloud Manager のすべてのドキュメント
    url: https://docs.netapp.com/us-en/cloud-manager-family
  - title: ONTAP ドキュメント： Amazon FSX
    url: "/index.html"
  - title: リリースノート
    url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: FSX for ONTAP について説明します
      url: "/start/concept-fsx-aws.html"
    - title: クイックスタート
      url: "/start/task-getting-started-fsx.html"
  - title: 要件
    entries:
    - title: ONTAP の FSX のアクセス許可を設定します
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: ONTAP の FSX のセキュリティグループルール
      url: "/requirements/reference-security-groups-fsx.html"
  - title: ONTAP には Amazon FSX を使用します
    entries:
    - title: 作業環境の作成と管理
      url: "/use/task-creating-fsx-working-environment.html"
    - title: ボリュームを作成してマウント
      url: "/use/task-add-fsx-volumes.html"
    - title: ボリュームとデータサービスを管理します
      url: "/use/task-manage-fsx-volumes.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/support/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/support/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: 新機能
      url: "/whats-new.html"
    - title: Amazon FSX for ONTAP の詳細をご覧ください
      url: "/start/concept-fsx-aws.html"
    - title: クイックスタート
      url: "/start/task-getting-started-fsx.html"
  - title: 要件
    links:
    - title: ONTAP の FSX のアクセス許可を設定します
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: ONTAP の FSX のセキュリティグループルール
      url: "/requirements/reference-security-groups-fsx.html"
  - title: ONTAP には Amazon FSX を使用します
    links:
    - title: 作業環境の作成と管理
      url: "/use/task-creating-fsx-working-environment.html"
    - title: ボリュームを作成してマウント
      url: "/use/task-add-fsx-volumes.html"
    - title: ボリュームとデータサービスを管理します
      url: "/use/task-manage-fsx-volumes.html"
  - title: 知識とサポート
    links:
    - title: サポートに登録します
      url: "/support/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/support/task-get-help.html"
  - title: ブログコミュニティ
    links:
    - title: ネットアップコミュニティ
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central のブログです
      url: https://cloud.netapp.com/blog
    - title: クラウドに関する Web セミナー
      url: https://cloud.netapp.com/events
product-family: {}
