---
settings:
  name: Amazon FSx for NetApp ONTAP
  platform: cloud
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Amazon FSx for NetApp ONTAP のドキュメント
    url: "/index.html"
  - title: リリースノート
    url: "/whats-new.html"
  - title: はじめに
    entries:
    - title: Amazon FSx for NetApp ONTAP の詳細をご確認ください
      url: "/start/concept-fsx-aws.html"
    - title: クイックスタート
      url: "/start/task-getting-started-fsx.html"
  - title: 要件
    entries:
    - title: 権限を設定します
      url: "/requirements/task-setting-up-permissions-fsx.html"
    - title: セキュリティグループのルール
      url: "/requirements/reference-security-groups-fsx.html"
  - title: Amazon FSx for NetApp ONTAP を使用します
    entries:
    - title: 作業環境を作成または検出します
      url: "/use/task-creating-fsx-working-environment.html"
    - title: 作業環境の管理
      url: "/use/task-manage-working-environment.html"
    - title: ボリュームを作成してマウントします
      url: "/use/task-add-fsx-volumes.html"
    - title: ボリュームを管理します
      url: "/use/task-manage-fsx-volumes.html"
    - title: Storage VMを追加および管理する
      url: "/use/task-add-fsx-svm.html"
  - title: 知識とサポート
    entries:
    - title: サポートに登録します
      url: "/support/task-support-registration.html"
    - title: ヘルプを表示します
      url: "/support/task-get-help.html"
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
