---
sidebar: sidebar 
permalink: use/task-manage-fsx-volumes.html 
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone 
summary: 'BlueXPを使用して"FSX for ONTAP のボリューム"クローン"スナップショットの管理"階層化ポリシーの変更を行うことができます' 
---
= Amazon FSx for NetApp ONTAP のボリュームを管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BlueXPを使用すると'FSX for ONTAP のボリューム'クローン'スナップショットの表示と管理'階層化ポリシーの変更を行うことができます



== ボリュームの詳細を表示します

ボリュームを作成したら、設定の詳細を確認できます。

. 作業環境を開きます。
+

NOTE: ボリューム名にカーソルを合わせると、ボリュームタイプを表示できます。

. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリュームの詳細を表示*」を選択します。




== ボリュームを編集します

作成したボリュームはいつでも変更できます。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリューム設定の編集*」を選択します。
. * 適用 * を選択します。




== ボリュームをクローニングする

ボリュームを作成したら、新しい Snapshot から読み書き可能な新しいボリュームを作成できます。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. [* Clone the volume]を選択します。
. クローンボリュームの名前を入力します。
. 「 * Clone * 」を選択します。




== ボリュームタグを管理します

ボリュームタグを追加、変更、または削除できます。BlueXPで追加されたタグはAWSコンソールに反映されます。タグをAWSコンソールと同期するのに最大1時間かかることがあります。


NOTE: BlueXPで作成したボリュームタグは、AWSと同期するまで編集できません。これには最大1時間かかることがあります。[Manage volume tags]*オプションがグレー表示されている場合は、AWSはまだボリュームタグを同期していません。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. [ボリュームタグの管理]*を選択します。
. [保存]*を選択して変更を適用します。




== Snapshot コピーを管理します

Snapshot コピーは、ボリュームのポイントインタイムコピーを提供します。Snapshot コピーを作成し、そのデータを新しいボリュームにリストアします。

.手順
. 作業環境を開きます。
. ボリュームタブを開き、*ボリュームの管理*を選択して、*保護処置*メニューを開きます。
. Snapshotコピーの管理に使用できるオプションを1つ選択します。
+
** * Snapshot コピーを作成します *
** * Snapshot コピーからのリストア *


. プロンプトに従って、選択した操作を完了します。




== 階層化ポリシーを変更します

ボリュームの階層化ポリシーを変更します。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量の管理*を選択して、*詳細アクション*メニューを開きます。
. 「*階層化ポリシーの変更*」を選択します。
. 新しいボリューム階層化ポリシーを選択し、 * Change * をクリックします。




== ボリュームを削除します

不要になったボリュームを削除します。

.作業を開始する前に
以前にBlueXPを使用してSnapMirror関係に含まれていたボリュームは削除できません。SnapMirror ボリュームは、 AWS 管理コンソールまたは CLI を使用して削除する必要があります。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリュームの削除*」を選択します。
. 作業環境の名前を入力し、ボリュームを削除することを確認します。ボリュームがBlueXPから完全に削除されるまでに、最大1時間かかる場合があります。



NOTE: クローンボリュームを削除しようとするとエラーが表示されます。
