---
sidebar: sidebar 
permalink: use/task-manage-fsx-volumes.html 
keywords: fsx for ontap, fsx, aws, delete volumes, delete nfs volumes, delete cifs volumes, tiering policy, mount path, get mount path, mount volume, delete volumes, snapshots, edit volume, clone volume, clone 
summary: Cloud Manager を使用して、 ONTAP のボリューム、クローン、 Snapshot の管理、および FSX for の階層化ポリシーの変更を行うことができます。 
---
= Amazon FSX for ONTAP のボリュームを管理します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cloud Managerを使用して、ONTAP のボリューム、クローン、Snapshotの表示と管理、およびFSX forの階層化ポリシーの変更を行うことができます。



== ボリュームの詳細を表示します

ボリュームを作成したら、設定の詳細を確認できます。

. 作業環境を開きます。
+

NOTE: ボリューム名にカーソルを合わせると、ボリュームタイプを表示できます。

. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリュームの詳細を表示*」を選択します。




== ボリュームを編集します

作成したボリュームはいつでも変更できます。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリューム設定の編集*」を選択します。
+
.. NFS の場合、サイズとタグを変更できます。
.. CIFS の場合、共有名、ユーザ、権限、および Snapshot ポリシーを必要に応じて変更できます。


. * 適用 * を選択します。




== ボリュームをクローニングする

ボリュームを作成したら、新しい Snapshot から読み書き可能な新しいボリュームを作成できます。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. [* Clone the volume]を選択します。
. クローンボリュームの名前を入力します。
. 「 * Clone * 」を選択します。




== Snapshot コピーを管理します

Snapshot コピーは、ボリュームのポイントインタイムコピーを提供します。Snapshot コピーを作成し、そのデータを新しいボリュームにリストアします。

.手順
. 作業環境を開きます。
. ボリュームタブを開き、*ボリュームの管理*を選択して、*保護処置*メニューを開きます。
. Snapshotコピーの管理に使用できるオプションを1つ選択します。
+
** * Snapshot コピーを作成します *
** * Snapshot コピーからのリストア *


. プロンプトに従って、選択した操作を完了します。




== 階層化ポリシーを変更します

ボリュームの階層化ポリシーを変更します。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量の管理*を選択して、*詳細アクション*メニューを開きます。
. 「*階層化ポリシーの変更*」を選択します。
. 新しいボリューム階層化ポリシーを選択し、 * Change * をクリックします。




== データをレプリケートして同期

Cloud Manager を使用して、ストレージ環境間でデータをレプリケートできます。ONTAP レプリケーション用に FSX を構成するには、を参照してください https://docs.netapp.com/us-en/cloud-manager-replication/task-replicating-data.html["システム間でのデータのレプリケーション"^]。

Cloud Manager の Cloud Sync を使用して、同期関係を作成できます。同期関係を設定するには、を参照してください https://docs.netapp.com/us-en/cloud-manager-sync/task-creating-relationships.html["同期関係を作成する"^]。



== ボリュームを削除します

不要になったボリュームを削除します。

以前に SnapMirror 関係に含まれていたボリュームは、 Cloud Manager を使用して削除することはできません。SnapMirror ボリュームは、 AWS 管理コンソールまたは CLI を使用して削除する必要があります。

.手順
. 作業環境を開きます。
. 音量タブを開き、*音量管理*を選択して*音量操作*メニューを開きます。
. 「*ボリュームの削除*」を選択します。
. 作業環境の名前を入力し、ボリュームを削除することを確認します。ボリュームが Cloud Manager から完全に削除されるまでに最大 1 時間かかることがあります。



NOTE: クローンボリュームを削除しようとするとエラーが表示されます。
