---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSx for NetApp ONTAPは、NetAppのONTAPストレージオペレーティングシステムを搭載したファイルシステムを起動して実行できるフルマネージドサービスです。 
---
= Amazon FSx for NetApp ONTAP の詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^] は、NetApp ONTAPストレージオペレーティングシステムを基盤とするファイルシステムを起動して実行できるフルマネージドサービスです。FSX for ONTAP は、ネットアップのお客様がオンプレミスで使用しているのと同じ機能、パフォーマンス、管理機能を、ネイティブの AWS サービスの簡易性、即応性、セキュリティ、拡張性で提供します。



== BlueXP  でのFSx for ONTAPの使用

BlueXP  キャンバスでは、FSx for ONTAP作業環境の作成と検出、System Managerやその他のBlueXP  サービスの使用、クレデンシャルの表示を行うことができます。FSx for ONTAPファイルシステムを使用するクレデンシャルとワークロードを管理する場合は、を使用します https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["BlueXP  ワークロードファクトリ"^]。

link:../use/task-creating-fsx-working-environment.html["BlueXP  でのFSx for ONTAPの使用に関する詳細情報"^]です。



== の機能

* ストレージ・デバイス ' ソフトウェア ' バックアップを構成または管理する必要はありません
* CIFS、iSCSI、NFSv3、NFSv4.x、 https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3"^]およびSMB v2.0-v3.1.1の各プロトコルをサポートしています。
* 使用頻度の低い IA （ストレージ・ティア）を使用して ' 低コストで事実上無制限のデータ・ストレージ容量を実現します
* Oracle RAC を含むレイテンシの影響を受けやすいアプリケーションでの実行が保証されています。
* バンドル価格と従量課金制のいずれかを選択できます




== BlueXPのその他の機能

* FSx for ONTAPはBlueXP  in_standard_modeでサポートされ、BlueXP  SaaSレイヤを活用してすべての機能を提供します。
+
を参照してください link:https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["BlueXPの導入モード"^] を参照してください。

* を使用します link:https://docs.netapp.com/us-en/bluexp-family/["BlueXP"^] AWSのコネクタとして、ボリュームの作成と管理、データのレプリケート、FSx for ONTAPとNetAppクラウドサービス（BlueXP分類、BlueXPのコピーと同期など）の統合が可能です。
* BlueXPは、人工知能（AI）ベースのテクノロジを使用して分類されるため、データのコンテキストを把握し、FSx for ONTAPアカウントに存在する機密データを特定するのに役立ちます。 https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["詳細はこちら。"^]。
* BlueXPのコピーと同期を使用すると、クラウドやオンプレミスの任意のターゲットへのデータ移行を自動化できます。 https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["詳細はこちら。"^]




== コネクタとリンクでFSx for ONTAPのすべての機能を活用

コネクタとリンクにより、BlueXP  とAmazon FSx for NetApp ONTAPの作業環境間の接続と信頼関係が確立されます。BlueXP  Connectorは、クラウドまたはオンプレミスネットワークで実行されるNetAppソフトウェアで、リンクはAWS Lambdaを使用してNetAppコードを実行します。BlueXP  の導入やFSx for ONTAP作業環境の作成にコネクタやリンクは必要ありませんが、FSx for ONTAPの機能をフルに活用するにはコネクタやリンクを使用する必要があります。

コネクタとリンクの詳細、およびそれらを使用するタイミングについては、以下を参照してください。

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["コネクタの詳細については、こちらをご覧ください"^]です。
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["リンクの詳細"^]です。




== コスト

FSX for ONTAP アカウントは、BlueXPではなくAWSによって管理されています。を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP スタートガイド"^]。

AWSでのコネクタの使用と、オプションのデータサービス（BlueXPのコピーと同期、BlueXPの分類など）の使用に関連する追加コストが発生します。



== サポートされている地域

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]



== サポートを受ける

Amazon FSx for NetApp ONTAP は、AWSファーストパーティの解決策 です。FSx for ONTAPの作業環境、インフラ、または本サービスを使用するソリューションに関する質問やテクニカルサポートの問題については、AWS管理コンソールのサポートセンターを使用してAWSでのサポートケースをオープンしてください。「FSx for ONTAP」サービスと該当するカテゴリを選択します。AWS サポートケースの作成に必要な残りの情報を指定します。

BlueXPまたはBlueXPストレージソリューションとサービスに関する一般的な質問については'オンラインのBlueXPチャットから始めることができます

BlueXP  またはBlueXP  ストレージソリューションおよびサービスに固有のテクニカルサポートの問題については、BlueXP  組織レベルのシリアル番号を使用してNetAppサポートチケットを発行できます。サポートを有効にする必要がlink:https://docs.netapp.com/us-en/bluexp-fsx-ontap/support/task-support-registration.html["BlueXP  組織の登録"^]あります。
