---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager 
summary: Amazon FSx for NetApp ONTAP は、ネットアップのONTAP ストレージオペレーティングシステムを搭載したファイルシステムを起動して実行できるフルマネージドサービスです。FSX for ONTAP は、ネットアップのお客様が現在オンプレミスで使用しているのと同じ機能、パフォーマンス、管理機能を、ネイティブの AWS サービスの簡易性、即応性、セキュリティ、拡張性で提供します。 
---
= Amazon FSx for NetApp ONTAP の詳細をご確認ください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^] は、 NetApp ONTAP ストレージ・オペレーティング・システムを搭載したファイル・システムの起動と実行を可能にするフルマネージド・サービスです。FSX for ONTAP は、ネットアップのお客様がオンプレミスで使用しているのと同じ機能、パフォーマンス、管理機能を、ネイティブの AWS サービスの簡易性、即応性、セキュリティ、拡張性で提供します。



== の機能

* ストレージ・デバイス ' ソフトウェア ' バックアップを構成または管理する必要はありません
* CIFS 、 NFSv3 、 NFSv4.x 、 SMB v2.v3.1.1 のプロトコルがサポートされます。
* 使用頻度の低い IA （ストレージ・ティア）を使用して ' 低コストで事実上無制限のデータ・ストレージ容量を実現します
* Oracle RAC を含むレイテンシの影響を受けやすいアプリケーションでの実行が保証されています。
* バンドル価格と従量課金制のいずれかを選択できます




== BlueXPのその他の機能

* を使用します link:https://docs.netapp.com/us-en/cloud-manager-family/["BlueXP"^] （Cloud Manager）とAWSのコネクタを使用して、ボリュームの作成と管理、データのレプリケート、FSx for ONTAPとネットアップのクラウドサービス（BlueXPの分類やBlueXPのコピーと同期（Cloud Sync）など）の統合を行うことができます。
* BlueXPの分類機能（Cloud Data Sense）は、人工知能（AI）ベースのテクノロジを使用して、データのコンテキストを把握し、FSx for ONTAPアカウントに存在する機密データを特定するのに役立ちます。 https://docs.netapp.com/us-en/cloud-manager-data-sense/concept-cloud-compliance.html["詳細はこちら。"^]。
* BlueXPのコピーと同期を使用すると、クラウドやオンプレミスの任意のターゲットへのデータ移行を自動化できます。 https://docs.netapp.com/us-en/cloud-manager-sync/concept-cloud-sync.html["詳細はこちら。"^]




== コスト

FSX for ONTAP アカウントは、BlueXPではなくAWSによって管理されています。を参照してください https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP スタートガイド"^]。

AWSでのコネクタの使用と、オプションのデータサービス（BlueXPのコピーと同期、BlueXPの分類など）の使用に関連する追加コストが発生します。



== サポートされている地域

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["サポート対象の Amazon リージョンを表示します。"^]



== サポートを受ける

Amazon FSx for NetApp ONTAP は、AWSファーストパーティの解決策 です。Amazon FSx for NetApp ONTAP のファイルシステム、インフラ、または本サービスを使用する解決策 に関する質問やテクニカルサポートの問題については、AWSコンソールのサポートセンターを使用してAWSに対するサポートケースをオープンしてください。「 FSX for ONTAP 」サービスと該当するカテゴリを選択します。AWS サポートケースの作成に必要な残りの情報を指定します。

BlueXPまたはBlueXPストレージソリューションとサービスに関する一般的な質問については'オンラインのBlueXPチャットから始めることができます

BlueXPまたはBlueXPのストレージソリューションとサービスに固有のテクニカルサポートの問題については、BlueXPアカウントレベルのシリアル番号を使用してネットアップサポートチケットを開くことができます。する必要があります link:https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/support/task-support-registration.html["BlueXPアカウントを登録します"^] をクリックしてサポートを有効にし
